apiVersion: v1
kind: Service
metadata:
  name: qr-frontend-service
spec:
  type: LoadBalancer
  selector:
      app: nextjs-client
      tier: frontend
  ports:
    - port: 80
      targetPort: 3000

