apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
type: Opaque 
stringData:
     BACKBLAZE_ACCESS_KEY: "00322351171ebe00000000001"
     BACKBLAZE_SECRET_KEY: "K003d8JnCy6EYhKBdlS4kqHXxsJNTrk"
     