apiVersion: v1
kind: Service
metadata:
  name: qr-backend-service
spec:
  type: ClusterIP
  selector:
    app: fastapi-server # this is how i labeled the server
    tier: backend
  ports:
    - port: 8000
      targetPort: 8000
